import type {
	BufferAttribute, Color, CubeTexture, FrontSide, Layers, Matrix3, Matrix4, NoBlending, Sphere, Texture, Vector3,
	Quaternion, WebGLRenderer,
	ClampToEdgeWrapping,
	DoubleSide,
	InterpolateDiscrete,
	InterpolateLinear,
	NoColorSpace,
	LinearFilter,
	LinearMipmapLinearFilter,
	LinearMipmapNearestFilter,
	MathUtils,
	MirroredRepeatWrapping,
	NearestFilter,
	NearestMipmapLinearFilter,
	NearestMipmapNearestFilter,
	PropertyBinding,
	RGBAFormat,
	RepeatWrapping,
	Scene,
	Source,
	SRGBColorSpace,
	CompressedTexture,

	PlaneGeometry,
	ShaderMaterial,
	Uniform,
	Mesh,
	PerspectiveCamera,
} from "three";

export type service = {
	BufferAttribute: typeof BufferAttribute,
	Color: typeof Color, CubeTexture: typeof CubeTexture, FrontSide: typeof FrontSide, Layers: typeof Layers, Matrix3: typeof Matrix3, Matrix4: typeof Matrix4, NoBlending: typeof NoBlending, Sphere: typeof Sphere, Texture: typeof Texture, Vector3: typeof Vector3,
	Quaternion: typeof Quaternion,
	WebGLRenderer: typeof WebGLRenderer,
	ClampToEdgeWrapping: typeof ClampToEdgeWrapping,
	DoubleSide: typeof DoubleSide,
	InterpolateDiscrete: typeof InterpolateDiscrete,
	InterpolateLinear: typeof InterpolateLinear,
	NoColorSpace: typeof NoColorSpace,
	LinearFilter: typeof LinearFilter,
	LinearMipmapLinearFilter: typeof LinearMipmapLinearFilter,
	LinearMipmapNearestFilter: typeof LinearMipmapNearestFilter,
	MathUtils: typeof MathUtils,
	MirroredRepeatWrapping: typeof MirroredRepeatWrapping,
	NearestFilter: typeof NearestFilter,
	NearestMipmapLinearFilter: typeof NearestMipmapLinearFilter,
	NearestMipmapNearestFilter: typeof NearestMipmapNearestFilter,
	PropertyBinding: typeof PropertyBinding,
	RGBAFormat: typeof RGBAFormat,
	RepeatWrapping: typeof RepeatWrapping,
	Scene: typeof Scene,
	Source: typeof Source,
	SRGBColorSpace: typeof SRGBColorSpace,
	CompressedTexture: typeof CompressedTexture,

	PlaneGeometry: typeof PlaneGeometry,
	ShaderMaterial: typeof ShaderMaterial,
	Uniform: typeof Uniform,
	Mesh: typeof Mesh,
	PerspectiveCamera: typeof PerspectiveCamera,

	//   BufferAttribute:any, Color:any, CubeTexture:any, FrontSide:any, Layers:any, Matrix3:any, Matrix4:any, NoBlending:any, Sphere:any, Texture:any, Vector3:any, WebGLRenderer:any,
	// 	ClampToEdgeWrapping:any,
	// 	DoubleSide:any,
	// 	InterpolateDiscrete:any,
	// 	InterpolateLinear:any,
	// 	NoColorSpace:any,
	// 	LinearFilter:any,
	// 	LinearMipmapLinearFilter:any,
	// 	LinearMipmapNearestFilter:any,
	// 	MathUtils:any,
	// 	MirroredRepeatWrapping:any,
	// 	NearestFilter:any,
	// 	NearestMipmapLinearFilter:any,
	// 	NearestMipmapNearestFilter:any,
	// 	PropertyBinding:any,
	// 	RGBAFormat:any,
	// 	RepeatWrapping:any,
	// 	Scene:any,
	// 	Source:any,
	// 	SRGBColorSpace:any,
	// 	CompressedTexture:any,

	// 	PlaneGeometry:any,
	// 	ShaderMaterial:any,
	// 	Uniform:any,
	// 	Mesh:any,
	// 	PerspectiveCamera:any,
}
