"use strict";
// import { S3 } from "@aws-sdk/client-s3";
// import { Upload } from "@aws-sdk/lib-storage";
Object.defineProperty(exports, "__esModule", { value: true });
exports.handleLogin = exports.init = void 0;
const Abtstract = require("backend-abstract");
const BackendService_1 = require("./application_layer/BackendService");
let init = () => Abtstract.init(BackendService_1.init);
exports.init = init;
let handleLogin = (account) => Abtstract.handleLogin(BackendService_1.handleLogin, account);
exports.handleLogin = handleLogin;
