"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.findAllPublishApps = exports.findPublishApp = exports.publishApp = exports.getAllPublishData = exports.getAllPublishProtocolConfigData = exports.getAllPublishProtocolData = exports.handleLogin = exports.init = void 0;
const ShopService = require("./application_layer/shop/ShopService");
const PublishAppService = require("./application_layer/publish/PublishAppService");
let init = (init) => init();
exports.init = init;
let handleLogin = (handleLogin, account) => handleLogin(account);
exports.handleLogin = handleLogin;
exports.getAllPublishProtocolData = ShopService.getAllPublishProtocolData;
exports.getAllPublishProtocolConfigData = ShopService.getAllPublishProtocolConfigData;
exports.getAllPublishData = ShopService.getAllPublishData;
exports.publishApp = PublishAppService.publish;
exports.findPublishApp = PublishAppService.findPublishApp;
exports.findAllPublishApps = PublishAppService.findAllPublishApps;
