"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getAllPublishData = exports.getAllPublishProtocolConfigData = exports.getAllPublishProtocolData = exports.handleLogin = exports.init = void 0;
const ShopService = require("./application_layer/shop/ShopService");
let init = (init) => init();
exports.init = init;
let handleLogin = (handleLogin, account) => handleLogin(account);
exports.handleLogin = handleLogin;
exports.getAllPublishProtocolData = ShopService.getAllPublishProtocolData;
exports.getAllPublishProtocolConfigData = ShopService.getAllPublishProtocolConfigData;
exports.getAllPublishData = ShopService.getAllPublishData;
