"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.findPublishPackage = exports.getAllPublishPackageInfos = exports.getAllPublishPackageEntryExtensionProtocols = exports.publishPackage = exports.publishElementContribute = exports.publishElementAssembleData = exports.getElementAssembleData = exports.getAllPublishNewestData = exports.findAllPublishAppsByAccount = exports.findPublishApp = exports.publishApp = exports.findPublishImplement = exports.getAllPublishImplementInfo = exports.getAllPublishProtocolConfigData = exports.getAllPublishProtocolData = exports.handleLogin = exports.init = void 0;
const MarketService = require("./application_layer/market/MarketService");
const PublishAppService = require("./application_layer/publish/PublishAppService");
const GetElementDataService = require("./application_layer/assemble_space/element_assemble/GetElementDataService");
const PublishElementContributeService = require("./application_layer/assemble_space/element_assemble/PublishElementContributeService");
const PublishPackageService = require("./application_layer/publish/PublishPackageService");
const PackageMarketService = require("./application_layer/market/PackageMarketService");
let init = (init, env) => init(env);
exports.init = init;
let handleLogin = (handleLogin, account) => handleLogin(account);
exports.handleLogin = handleLogin;
exports.getAllPublishProtocolData = MarketService.getAllPublishProtocolData;
exports.getAllPublishProtocolConfigData = MarketService.getAllPublishProtocolConfigData;
exports.getAllPublishImplementInfo = MarketService.getAllPublishImplementInfo;
exports.findPublishImplement = MarketService.findPublishImplement;
exports.publishApp = PublishAppService.publish;
exports.findPublishApp = PublishAppService.findPublishApp;
exports.findAllPublishAppsByAccount = PublishAppService.findAllPublishAppsByAccount;
exports.getAllPublishNewestData = GetElementDataService.getAllPublishNewestData;
exports.getElementAssembleData = GetElementDataService.getElementAssembleData;
exports.publishElementAssembleData = PublishElementContributeService.publishElementAssembleData;
exports.publishElementContribute = PublishElementContributeService.publishElementContribute;
exports.publishPackage = PublishPackageService.publish;
exports.getAllPublishPackageEntryExtensionProtocols = PackageMarketService.getAllPublishPackageEntryExtensionProtocols;
exports.getAllPublishPackageInfos = PackageMarketService.getAllPublishPackageInfos;
exports.findPublishPackage = PackageMarketService.findPublishPackage;
