import { action, category, emitterType, feature, instance, weaponType, model, particleImage, propName, damageEffect, meleeSubEffect, rangedSubEffect, emitterSubEffect } from "meta3d-action-mod-unit-publish-to-game-protocol/src/UnitType"
import { language, languageKey, languageVariableKey, languageTextData, languageTextDataByVariable } from "./Type"

export let getTextData = (): languageTextData => {
    return {
        [language.Chinese]: {
            [languageKey.Level]: "级别",
            [languageKey.Count]: "数量",
            [languageKey.CountFactor]: "数量系数",
            [languageKey.DropRate]: "爆率",
            [languageKey.Difficulty]: "难度",
            [languageKey.Weight]: "权重",
            [languageKey.GenerateRate]: "出现的概率",
            [languageKey.AddGenerateDataInAttackCityLevel]: "攻击城市关卡增加生成数据",
            [languageKey.AddGenerateDataInProtectCityLevel]: "防卫城市关卡增加生成数据",
            [languageKey.AddGenerateDataInBossLevel]: "boss关卡增加生成数据",
            [languageKey.ForSmallUnit]: "针对小型单位",
            [languageKey.ForBigUnit]: "针对大型单位",
            [languageKey.DisplayNameCN]: "模组名称（中文）",
            [languageKey.DisplayNameEN]: "模组名称（英文）",
            [languageKey.UploadModIcon]: "上传模组图标",
            [languageKey.IsPublic]: "是否公开（如果不公开，则仅可在调试模式中订阅该模组）",
            [languageKey.Description]: "描述（包含中文、英文）（支持Markdown）",
            [languageKey.PublishToGame]: "发布到游戏",
            [languageKey.Cancel]: "取消",
            [languageKey.Loading]: "加载中......",
            [languageKey.Publishing]: "正在发布中...",
            [languageKey.Success]: "成功",
            [languageKey.Fail]: "失败",

            [languageKey.NeedDisplayNameCN]: "需要输入模组名称（中文）",
            [languageKey.NeedDisplayNameEN]: "需要输入模组名称（英文）",
            [languageKey.NeedDescription]: "需要输入描述",
            [languageKey.NeedModIcon]: "需要上传模组图标",
            [languageKey.NeedAllSkillObject]: "需要加入针对小型单位和大型单位的技能",
            [languageKey.NeedAtLeastOneGenerateData]: "需要为至少一个关卡加入生成数据",
            [languageKey.NeedSmallSkillObjectEmitterData]: "需要加入针对小型单位的技能->弹药数据",
            [languageKey.NeedBigSkillObjectEmitterData]: "需要加入针对大型单位的技能->弹药数据",


            [category.EliteGiantess]: "精英巨大娘",
            [model.EliteGiantess1]: "精英巨大娘1",
            [model.EliteGiantess2]: "精英巨大娘2",
            [model.EliteGiantess3]: "精英巨大娘3",
            [model.EliteGiantess4]: "精英巨大娘4",
            [model.EliteGiantess5]: "精英巨大娘5",
            [model.EliteGiantess6]: "精英巨大娘6",
            [model.EliteGiantess7]: "精英巨大娘7",
            [model.EliteGiantess8]: "精英巨大娘8",
            [model.EliteGiantess9]: "精英巨大娘9",
            [model.EliteGiantess10]: "精英巨大娘10",
            [action.StompLight]: "轻踩",
            [action.StompHeavy]: "重踩",
            [action.Kick1]: "踢1",
            [action.Kick2]: "踢2",
            [action.Bencao]: "Bencao踢",
            [action.Boxing]: "拳击",
            [action.ChickenDance]: "鸡舞",
            [action.CrossJumps]: "跨跳",
            [action.JumpHeavy]: "重跳",
            [action.JumpLight]: "轻跳",
            [action.KickTwice]: "踢两次",
            [action.LegSweep]: "扫腿",
            [action.Punch]: "直拳",
            [action.PunchCombo]: "直拳组合",
            [action.RumbaDance]: "Rumba舞",
            [action.Speedbag]: "快速击打",
            [action.TwistRub]: "脚碾",
            [action.Cast]: "施法",
            [propName.AddHp1]: "加血（小）",
            [propName.AddHp2]: "加血（中）",
            [propName.LaserBullet]: "激光子弹",
            [feature.DamageBigger]: "受击变大",
            [feature.PassiveBigger]: "被动变大",
            [feature.PoisonSingle]: "中毒",
            [weaponType.Body]: "身体伤害",
            [weaponType.Common]: "普通伤害",
            [weaponType.Effect]: "效果伤害",
            [weaponType.EffectSelf]: "效果自身伤害",
            [weaponType.Explode]: "爆炸伤害",
            [weaponType.Impact]: "冲击伤害",
            [weaponType.Magic]: "魔法伤害",
            [weaponType.Power]: "神圣伤害",
            [damageEffect.RangeDamage]: "范围伤害",
            [damageEffect.Repel]: "击飞",
            [meleeSubEffect.FootDamageDecal]: "地裂贴花",
            [meleeSubEffect.StompDust]: "踩踏灰尘",
            [rangedSubEffect.FireballHit]: "击中火球",
            [rangedSubEffect.ShellExplode]: "炮弹爆炸",
            [emitterSubEffect.ShellEmit]: "炮弹发射",
            [emitterType.Particle]: "粒子",
            [emitterType.Instance]: "实例",
            [instance.Arrow1]: "箭头1",
            [instance.Missile1]: "导弹1",
        },
        [language.English]: {
            [languageKey.Level]: "Level",
            [languageKey.Count]: "Count",
            [languageKey.CountFactor]: "Count Factor",
            [languageKey.DropRate]: "Drop Rate",
            [languageKey.Difficulty]: "Difficulty",
            [languageKey.Weight]: "Weight",
            [languageKey.GenerateRate]: "Spawn Chance",
            [languageKey.AddGenerateDataInAttackCityLevel]: "Add Generation Data in Attack City Levels",
            [languageKey.AddGenerateDataInProtectCityLevel]: "Add Generation Data in Defend City Levels",
            [languageKey.AddGenerateDataInBossLevel]: "Add Generation Data in Boss Levels",
            [languageKey.ForSmallUnit]: "For Small Units",
            [languageKey.ForBigUnit]: "For Large Units",
            [languageKey.DisplayNameCN]: "Mod Name (Chinese)",
            [languageKey.DisplayNameEN]: "Mod Name (English)",
            [languageKey.UploadModIcon]: "Upload Mod Icon",
            [languageKey.IsPublic]: "Public (If not public, the mod can only be subscribed in debug mode)",
            [languageKey.Description]: "Description (Chinese and English) (Markdown supported)",
            [languageKey.PublishToGame]: "Publish to Game",
            [languageKey.Cancel]: "Cancel",
            [languageKey.Loading]: "Loading...",
            [languageKey.Publishing]: "Publishing...",
            [languageKey.Success]: "Success",
            [languageKey.Fail]: "Fail",

            [languageKey.NeedDisplayNameCN]: "Chinese mod name is required",
            [languageKey.NeedDisplayNameEN]: "English mod name is required",
            [languageKey.NeedDescription]: "Description is required",
            [languageKey.NeedModIcon]: "Mod icon is required",
            [languageKey.NeedAllSkillObject]: "Skills for both small and large units are required",
            [languageKey.NeedAtLeastOneGenerateData]: "Generation data for at least one level is required",
            [languageKey.NeedSmallSkillObjectEmitterData]: "Ammo data for small unit skills is required",
            [languageKey.NeedBigSkillObjectEmitterData]: "Ammo data for large unit skills is required",

            [category.EliteGiantess]: "Elite Giantess",
            [model.EliteGiantess1]: "Elite Giantess 1",
            [model.EliteGiantess2]: "Elite Giantess 2",
            [model.EliteGiantess3]: "Elite Giantess 3",
            [model.EliteGiantess4]: "Elite Giantess 4",
            [model.EliteGiantess5]: "Elite Giantess 5",
            [model.EliteGiantess6]: "Elite Giantess 6",
            [model.EliteGiantess7]: "Elite Giantess 7",
            [model.EliteGiantess8]: "Elite Giantess 8",
            [model.EliteGiantess9]: "Elite Giantess 9",
            [model.EliteGiantess10]: "Elite Giantess 10",
            [action.StompLight]: "Light Stomp",
            [action.StompHeavy]: "Heavy Stomp",
            [action.Kick1]: "Kick 1",
            [action.Kick2]: "Kick 2",
            [action.Bencao]: "Bencao Kick",
            [action.Boxing]: "Boxing",
            [action.ChickenDance]: "Chicken Dance",
            [action.CrossJumps]: "Cross Jumps",
            [action.JumpHeavy]: "Heavy Jump",
            [action.JumpLight]: "Light Jump",
            [action.KickTwice]: "Double Kick",
            [action.LegSweep]: "Leg Sweep",
            [action.Punch]: "Punch",
            [action.PunchCombo]: "Punch Combo",
            [action.RumbaDance]: "Rumba Dance",
            [action.Speedbag]: "Speed Bag",
            [action.TwistRub]: "Twist and Rub",
            [action.Cast]: "Cast",
            [propName.AddHp1]: "Heal (Small)",
            [propName.AddHp2]: "Heal (Medium)",
            [propName.LaserBullet]: "Laser Bullet",
            [feature.DamageBigger]: "Grow on Hit",
            [feature.PassiveBigger]: "Passive Growth",
            [feature.PoisonSingle]: "Poison",
            [weaponType.Body]: "Body Damage",
            [weaponType.Common]: "Common Damage",
            [weaponType.Effect]: "Effect Damage",
            [weaponType.EffectSelf]: "Self Effect Damage",
            [weaponType.Explode]: "Explosive Damage",
            [weaponType.Impact]: "Impact Damage",
            [weaponType.Magic]: "Magic Damage",
            [weaponType.Power]: "Holy Damage",
            [damageEffect.RangeDamage]: "Area Damage",
            [damageEffect.Repel]: "Knockback",
            [meleeSubEffect.FootDamageDecal]: "Ground Crack Decal",
            [meleeSubEffect.StompDust]: "Stomp Dust",
            [rangedSubEffect.FireballHit]: "Fireball Hit",
            [rangedSubEffect.ShellExplode]: "Shell Explosion",
            [emitterSubEffect.ShellEmit]: "Shell Emission",
            [emitterType.Particle]: "Particle",
            [emitterType.Instance]: "Instance",
            [instance.Arrow1]: "Arrow 1",
            [instance.Missile1]: "Missile 1",
        },
    }
}

export let getTextDataByVariable = (): languageTextDataByVariable => {
    return {
        [language.Chinese]: {
            [languageVariableKey.LimitMaxCount]: (value: number) => `最多选择${value}个`,
        },
        [language.English]: {
            [languageVariableKey.LimitMaxCount]: (value: number) => `Can select ${value} at most`,
        },
    }
}