import { action, category, emitterType, feature, instance, weaponType, model, particleImage, propName, damageEffect, meleeSubEffect, rangedSubEffect, emitterSubEffect, behaviourMode, idleMode, nearAttackTargetMode, attackMode, remoteAttackMode, behaviourModeKey, idleModeKey, nearAttackTargetModeKey, attackModeKey } from "meta3d-action-mod-unit-publish-to-game-protocol/src/UnitType"
import { language, languageKey, languageVariableKey, languageTextData, languageTextDataByVariable } from "./Type"

export let getTextData = (): languageTextData => {
    return {
        [language.Chinese]: {
            [languageKey.Level]: "级别",
            [languageKey.Count]: "数量",
            [languageKey.CountFactor]: "每次出现的数量系数",
            [languageKey.DropRate]: "爆率",
            [languageKey.Difficulty]: "难度",
            [languageKey.Weight]: "权重",
            [languageKey.GenerateRate]: "出现的概率",
            [languageKey.AddGenerateDataInAttackCityLevel]: "攻击城市关卡增加生成数据",
            [languageKey.AddGenerateDataInProtectCityLevel]: "防卫城市关卡增加生成数据",
            [languageKey.AddGenerateDataInBossLevel]: "boss关卡增加生成数据",
            [languageKey.ForSmallUnit]: "针对小型单位",
            [languageKey.ForBigUnit]: "针对大型单位",
            [languageKey.ForAllUnit]: "针对所有单位",
            [languageKey.DisplayNameCN]: "模组名称（中文）",
            [languageKey.DisplayNameEN]: "模组名称（英文）",
            [languageKey.UploadModIcon]: "上传模组图标",
            [languageKey.IsPublic]: "是否公开（如果不公开，则仅可在调试模式中订阅该模组）",
            [languageKey.Description]: "描述（包含中文、英文）（支持Markdown）",
            [languageKey.PublishToGame]: "发布到游戏",
            [languageKey.Cancel]: "取消",
            [languageKey.Loading]: "加载中......",
            [languageKey.Publishing]: "正在发布中...",
            [languageKey.Success]: "成功",
            [languageKey.Fail]: "失败",

            [languageKey.NeedDisplayNameCN]: "需要输入模组名称（中文）",
            [languageKey.NeedDisplayNameEN]: "需要输入模组名称（英文）",
            [languageKey.NeedDescription]: "需要输入描述",
            [languageKey.NeedModIcon]: "需要上传模组图标",
            [languageKey.NeedAllSkillObject]: "需要加入针对小型单位和大型单位的技能",
            [languageKey.NeedAtLeastOneGenerateData]: "需要为至少一个关卡加入生成数据",
            [languageKey.NeedSmallSkillObjectEmitterData]: "需要加入针对小型单位的技能->弹药数据",
            [languageKey.NeedBigSkillObjectEmitterData]: "需要加入针对大型单位的技能->弹药数据",
            [languageKey.NeedAllSkillObjectEmitterData]: "需要加入针对所有单位的技能->弹药数据",
            [languageKey.NeedLOD1LOD2SnapshotModelFile]: "需要上传LOD1和LOD2的模型FBX文件和模型快照",

            [languageKey.Melee]: "近战",
            [languageKey.Ranged]: "远程",
            [languageKey.Assistant]: "辅助",


            [category.EliteGiantess]: "精英巨大娘",
            [category.Soldier]: "士兵",
            [model.EliteGiantess1]: "精英巨大娘1",
            [model.EliteGiantess2]: "精英巨大娘2",
            [model.EliteGiantess3]: "精英巨大娘3",
            [model.EliteGiantess4]: "精英巨大娘4",
            [model.EliteGiantess5]: "精英巨大娘5",
            [model.EliteGiantess6]: "精英巨大娘6",
            [model.EliteGiantess7]: "精英巨大娘7",
            [model.EliteGiantess8]: "精英巨大娘8",
            [model.EliteGiantess9]: "精英巨大娘9",
            [model.EliteGiantess10]: "精英巨大娘10",
            [model.Soldier1]: "士兵1",
            [model.Soldier2]: "士兵2",
            [model.Soldier3]: "士兵3",
            [model.Soldier4]: "士兵4",
            [model.Soldier5]: "士兵5",
            // [model.EliteGiantess11]: "精英巨大娘11",

            [action.Death]: "死亡",
            [action.DeathHeadshot]: "爆头",
            [action.Idle]: "空闲",
            [action.Lie]: "躺",
            [action.PickedControlled]: "被控制",
            [action.Shake]: "硬直",
            [action.StandupFromLie]: "起身",
            [action.Walk]: "走",
            [action.Run]: "跑",
            [action.Sprint]: "冲刺",
            [action.JumpForward]: "往前跳",

            [action.StompLight]: "轻踩",
            [action.StompHeavy]: "重踩",
            [action.Kick1]: "踢1",
            [action.Kick2]: "踢2",
            [action.Bencao]: "Bencao踢",
            [action.Boxing]: "拳击",
            [action.ChickenDance]: "鸡舞",
            [action.CrossJumps]: "跨跳",
            [action.JumpHeavy]: "重跳",
            [action.JumpLight]: "轻跳",
            [action.KickTwice]: "踢两次",
            [action.LegSweep]: "扫腿",
            [action.Punch]: "直拳",
            [action.PunchCombo]: "直拳组合",
            [action.RumbaDance]: "Rumba舞",
            [action.Speedbag]: "快速击打",
            [action.TwistRub]: "脚碾",
            [action.Cast]: "施法",

            [action.Slash1]: "劈1",
            [action.Slash2]: "劈2",
            [action.Slash3]: "劈3",
            [action.Slash4]: "劈4",
            [action.SlashCombo1]: "劈组合1",
            [action.SlashCombo2]: "劈组合2",
            [action.SlashCombo3]: "劈组合3",
            [action.Swipe1]: "重击1",
            [action.Cast1]: "施法1",
            [action.Cast2]: "施法2",
            [action.Cast3]: "施法3",
            [action.Charge]: "冲锋",
            [action.MeleeKick1]: "近踢1",
            [action.Shoot1]: "射击1",
            [action.Shoot2]: "射击2",
            [action.Shoot3]: "射击3",
            [action.Shoot4]: "射击4",

            [propName.AddHp1]: "加血（小）",
            [propName.AddHp2]: "加血（中）",
            [propName.AddHp3]: "加血（大）",
            [propName.AddHp4]: "加血（极大）",
            [propName.AddExcitement1]: "增加兴奋值（小）",
            [propName.AddExcitement2]: "增加兴奋值（中）",
            [propName.AddExcitement3]: "增加兴奋值（大）",
            [propName.AddExcitement4]: "增加兴奋值（极大）",
            [propName.LaserBullet]: "激光子弹",
            [propName.RocketBullet]: "火箭弹",
            ["Weapon_BiggerBulletGun"]: "变大子弹",
            ["Weapon_SmallerBulletGun"]: "变小子弹",
            ["Weapon_ShotBulletGun"]: "散弹枪子弹",
            ["Weapon_SubMachineBulletGun"]: "冲锋枪子弹",
            ["Prop_Other_Run"]: "疾跑",
            ["Prop_Other_SmallerWater"]: "缩小药水",
            ["Prop_Other_Strong"]: "霸体",
            [feature.DamageBigger]: "受击变大：受到攻击后会变大",
            [feature.PassiveBigger]: "被动变大：击败单位后变大",
            [feature.PoisonSingle]: "中毒：被攻击的单位可能中毒",
            [feature.IceSingle]: "冰霜之触：被攻击的单位可能减速",
            [feature.StressProtect]: "应激防护：受到大于25%自己最大生命值的攻击时，大幅降低受到的伤害, 持续几秒",
            [feature.FragileGrowth]: "脆弱之息：获得伤害的一定百分比的生命汲取,但受到的伤害增加50%",
            [feature.DoorShield]: "门板重盾：移动速度降低一定百分比,有一定百分比几率减少受到的伤害",
            [feature.DecreaseScale]: "缩小攻击：攻击有一定概率使巨大娘缩小",
            [feature.Pull]: "牵引黑洞：范围攻击有一定概率使将受影响单位牵引到命中点附近（对大于50米的单位无效）",
            [feature.DefenseIncreaseDefense]: "越打越硬：受到攻击后增加防御, 持续3秒",
            [feature.HpRatioDirect]: "血多伤高：您的血量百分比越高，伤害越高；反之伤害越低",
            [feature.HpRatioInverse]: "血少伤高：您的血量百分比越低，伤害越高；反之伤害越低",
            [feature.ShootDistanceDirect]: "射距正比：射击距离越近，伤害越高；反之伤害越低",
            [feature.ShootDistanceInverse]: "射距反比：射击距离越远，伤害越高；反之伤害越低",
            [weaponType.Body]: "身体伤害",
            [weaponType.Common]: "普通伤害",
            [weaponType.Effect]: "效果伤害",
            [weaponType.EffectSelf]: "效果自身伤害",
            [weaponType.Explode]: "爆炸伤害",
            [weaponType.Impact]: "冲击伤害",
            [weaponType.Magic]: "魔法伤害",
            [weaponType.Power]: "神圣伤害",
            [damageEffect.RangeDamage]: "范围伤害",
            [damageEffect.Repel]: "击飞",
            [meleeSubEffect.FootDamageDecal]: "地裂贴花",
            [meleeSubEffect.StompDust]: "踩踏灰尘",
            [rangedSubEffect.FireballHit]: "击中火球",
            [rangedSubEffect.BasicBulletHit]: "击中基础子弹",
            [rangedSubEffect.LaserBulletHit]: "击中激光子弹",
            [rangedSubEffect.ShellExplode]: "炮弹爆炸",
            [emitterSubEffect.ShellEmit]: "炮弹发射",
            [emitterType.Particle]: "粒子",
            [emitterType.Instance]: "实例",
            [instance.Arrow1]: "箭头1",
            [instance.Arrow2]: "箭头2",
            [instance.Missile1]: "导弹1",
            [instance.Missile2]: "导弹2",
            [instance.Missile3]: "导弹3",
            [instance.Missile4]: "导弹4",
            [instance.Missile5]: "导弹5",
            [instance.Missile6]: "导弹6",
            [instance.Missile7]: "导弹7",
            [instance.Missile8]: "导弹8",
            [instance.Missile9]: "导弹9",
            [instance.Building1]: "建筑1",
            [instance.Building2]: "建筑2",
            [instance.Weapon1]: "武器1",
            [instance.Weapon2]: "武器2",
            [instance.Airplane1]: "飞机1",
            [behaviourMode.FindEnemy]: "寻找敌人",
            [behaviourMode.EscapeWhenEnemeyNear]: "当敌人接近时逃跑",
            [idleMode.WaitInPlace]: "原地等待",
            [idleMode.RoamAndWander]: "漫游",
            [nearAttackTargetMode.None]: "无",
            // [nearAttackTargetMode.Charge]: "冲锋",
            // [nearAttackTargetMode.JumpForward]: "跳跃",
            [attackMode.SideShift]: "侧移",
            [attackMode.KeepDistance]: "保持距离",
            [remoteAttackMode.ShootAroundObstacles]: "绕过障碍物射击",
            [behaviourModeKey.FindEnemyDistanceFactor]: "寻找敌人距离系数",
            [behaviourModeKey.PursuitDistanceFactor]: "追击距离系数",
            [behaviourModeKey.EscapeDistanceFactor]: "逃跑距离系数",
            [behaviourModeKey.NearDistanceFactor]: "敌人接近距离系数",
            [idleModeKey.RoamAndWanderDistanceFactor]: "漫游距离系数",
            [nearAttackTargetModeKey.CD]: "冷却时间",
            [nearAttackTargetModeKey.DamageInterval]: "伤害时间间隔",
            [nearAttackTargetModeKey.DistanceFactor]: "距离系数",
            [nearAttackTargetModeKey.ForceFactor]: "力系数",
            [nearAttackTargetModeKey.SpeedFactor]: "速度系数",
        },
        [language.English]: {
            [languageKey.Level]: "Level",
            [languageKey.Count]: "Count",
            [languageKey.CountFactor]: "Count factor per Spawn",
            [languageKey.DropRate]: "Drop Rate",
            [languageKey.Difficulty]: "Difficulty",
            [languageKey.Weight]: "Weight",
            [languageKey.GenerateRate]: "Spawn Chance",
            [languageKey.AddGenerateDataInAttackCityLevel]: "Add Generation Data in Attack City Levels",
            [languageKey.AddGenerateDataInProtectCityLevel]: "Add Generation Data in Defend City Levels",
            [languageKey.AddGenerateDataInBossLevel]: "Add Generation Data in Boss Levels",
            [languageKey.ForSmallUnit]: "For Small Units",
            [languageKey.ForBigUnit]: "For Large Units",
            [languageKey.ForAllUnit]: "For All Units",
            [languageKey.DisplayNameCN]: "Mod Name (Chinese)",
            [languageKey.DisplayNameEN]: "Mod Name (English)",
            [languageKey.UploadModIcon]: "Upload Mod Icon",
            [languageKey.IsPublic]: "Public (If not public, the mod can only be subscribed in debug mode)",
            [languageKey.Description]: "Description (Chinese and English) (Markdown supported)",
            [languageKey.PublishToGame]: "Publish to Game",
            [languageKey.Cancel]: "Cancel",
            [languageKey.Loading]: "Loading...",
            [languageKey.Publishing]: "Publishing...",
            [languageKey.Success]: "Success",
            [languageKey.Fail]: "Fail",

            [languageKey.NeedDisplayNameCN]: "Chinese mod name is required",
            [languageKey.NeedDisplayNameEN]: "English mod name is required",
            [languageKey.NeedDescription]: "Description is required",
            [languageKey.NeedModIcon]: "Mod icon is required",
            [languageKey.NeedAllSkillObject]: "Skills for both small and large units are required",
            [languageKey.NeedAtLeastOneGenerateData]: "Generation data for at least one level is required",
            [languageKey.NeedSmallSkillObjectEmitterData]: "Ammo data for small unit skills is required",
            [languageKey.NeedBigSkillObjectEmitterData]: "Ammo data for large unit skills is required",
            [languageKey.NeedAllSkillObjectEmitterData]: "Ammo data for all unit skills is required",
            [languageKey.NeedLOD1LOD2SnapshotModelFile]: "LOD1 and LOD2 model file and snapshot are required",

            [languageKey.Melee]: "Melee",
            [languageKey.Ranged]: "Ranged",
            [languageKey.Assistant]: "Assistant",

            [category.EliteGiantess]: "Elite Giantess",
            [category.Soldier]: "Soldier",
            [model.EliteGiantess1]: "Elite Giantess 1",
            [model.EliteGiantess2]: "Elite Giantess 2",
            [model.EliteGiantess3]: "Elite Giantess 3",
            [model.EliteGiantess4]: "Elite Giantess 4",
            [model.EliteGiantess5]: "Elite Giantess 5",
            [model.EliteGiantess6]: "Elite Giantess 6",
            [model.EliteGiantess7]: "Elite Giantess 7",
            [model.EliteGiantess8]: "Elite Giantess 8",
            [model.EliteGiantess9]: "Elite Giantess 9",
            [model.EliteGiantess10]: "Elite Giantess 10",
            [model.Soldier1]: "Soldier 1",
            [model.Soldier2]: "Soldier 2",
            [model.Soldier3]: "Soldier 3",
            [model.Soldier4]: "Soldier 4",
            [model.Soldier5]: "Soldier 5",
            // [model.EliteGiantess11]: "Elite Giantess 11",

            [action.Death]: "Death",
            [action.DeathHeadshot]: "Deathshot Head",
            [action.Idle]: "Idle",
            [action.Lie]: "Lie",
            [action.PickedControlled]: "Picked Controlled",
            [action.Shake]: "Shake",
            [action.StandupFromLie]: "Standup from Lie",
            [action.Walk]: "Walk",
            [action.Run]: "Run",
            [action.Sprint]: "Sprint",
            [action.JumpForward]: "Jump Forward",

            [action.StompLight]: "Light Stomp",
            [action.StompHeavy]: "Heavy Stomp",
            [action.Kick1]: "Kick 1",
            [action.Kick2]: "Kick 2",
            [action.Bencao]: "Bencao Kick",
            [action.Boxing]: "Boxing",
            [action.ChickenDance]: "Chicken Dance",
            [action.CrossJumps]: "Cross Jumps",
            [action.JumpHeavy]: "Heavy Jump",
            [action.JumpLight]: "Light Jump",
            [action.KickTwice]: "Kick Twice",
            [action.LegSweep]: "Leg Sweep",
            [action.Punch]: "Punch",
            [action.PunchCombo]: "Punch Combo",
            [action.RumbaDance]: "Rumba Dance",
            [action.Speedbag]: "Speedbag",
            [action.TwistRub]: "Rubbing",
            [action.Cast]: "Cast",

            [action.Slash1]: "Slash 1",
            [action.Slash2]: "Slash 2",
            [action.Slash3]: "Slash 3",
            [action.Slash4]: "Slash 4",
            [action.SlashCombo1]: "Slash Combo 1",
            [action.SlashCombo2]: "Slash Combo 2",
            [action.SlashCombo3]: "Slash Combo 3",
            [action.Swipe1]: "Swipe 1",
            [action.Cast1]: "Cast 1",
            [action.Cast2]: "Cast 2",
            [action.Cast3]: "Cast 3",
            [action.Charge]: "Charge",
            [action.MeleeKick1]: "Melee Kick 1",
            [action.Shoot1]: "Shoot 1",
            [action.Shoot2]: "Shoot 2",
            [action.Shoot3]: "Shoot 3",
            [action.Shoot4]: "Shoot 4",

            [propName.AddHp1]: "Heal (Small)",
            [propName.AddHp2]: "Heal (Medium)",
            [propName.AddHp3]: "Heal (Large)",
            [propName.AddHp4]: "Heal (Very Large)",
            [propName.AddExcitement1]: "Increase Excitement (Small)",
            [propName.AddExcitement2]: "Increase Excitement (Medium)",
            [propName.AddExcitement3]: "Increase Excitement (Large)",
            [propName.AddExcitement4]: "Increase Excitement (Very Large)",
            [propName.LaserBullet]: "Laser Bullet",
            [propName.RocketBullet]: "Rocket",
            ["Weapon_BiggerBulletGun"]: "Enlarge Bullet",
            ["Weapon_SmallerBulletGun"]: "Shrink Bullet",
            ["Weapon_ShotBulletGun"]: "Shotgun Bullet",
            ["Weapon_SubMachineBulletGun"]: "SMG Bullet",
            ["Prop_Other_Run"]: "Sprint",
            ["Prop_Other_SmallerWater"]: "Shrinking Potion",
            ["Prop_Other_Strong"]: "Super Armor",
            [feature.DamageBigger]: "Grow on Hit: Grows larger after being hit.",
            [feature.PassiveBigger]: "Passive Growth: Grows larger after defeating a unit.",
            [feature.PoisonSingle]: "Poison: Attacked units may be poisoned.",
            [feature.IceSingle]: "Frost Touch: Attacked units may be slowed.",
            [feature.StressProtect]: "Stress Protection: When taking damage exceeding 25% of max HP, greatly reduces damage taken for a few seconds.",
            [feature.FragileGrowth]: "Fragile Breath: Gains life steal equal to a percentage of damage dealt, but takes 50% increased damage.",
            [feature.DoorShield]: "Door Shield: Reduces movement speed by a certain percentage, and has a chance to reduce damage taken.",
            [feature.DecreaseScale]: "Shrink Attack: Attacks have a chance to shrink the giantess.",
            [feature.Pull]: "Black Hole Pull: Area attacks have a chance to pull affected units to the hit point (ineffective on units larger than 50 meters).",
            [feature.DefenseIncreaseDefense]: "Tougher on Hit: Increases defense after being hit for 3 seconds.",
            [feature.HpRatioDirect]: "HP Direct Scaling: The higher your HP percentage, the higher your damage; the lower your HP percentage, the lower your damage.",
            [feature.HpRatioInverse]: "HP Inverse Scaling: The lower your HP percentage, the higher your damage; the higher your HP percentage, the lower your damage.",
            [feature.ShootDistanceDirect]: "Range Direct Scaling: The closer your shooting distance, the higher your damage; the farther, the lower your damage.",
            [feature.ShootDistanceInverse]: "Range Inverse Scaling: The farther your shooting distance, the higher your damage; the closer, the lower your damage.",
            [weaponType.Body]: "Body Damage",
            [weaponType.Common]: "Common Damage",
            [weaponType.Effect]: "Effect Damage",
            [weaponType.EffectSelf]: "Self Effect Damage",
            [weaponType.Explode]: "Explosive Damage",
            [weaponType.Impact]: "Impact Damage",
            [weaponType.Magic]: "Magic Damage",
            [weaponType.Power]: "Holy Damage",
            [damageEffect.RangeDamage]: "Area Damage",
            [damageEffect.Repel]: "Knockback",
            [meleeSubEffect.FootDamageDecal]: "Ground Crack Decal",
            [meleeSubEffect.StompDust]: "Stomp Dust",
            [rangedSubEffect.FireballHit]: "Fireball Hit",
            [rangedSubEffect.BasicBulletHit]: "Basic Bullet Hit",
            [rangedSubEffect.LaserBulletHit]: "Laser Bullet Hit",
            [rangedSubEffect.ShellExplode]: "Shell Explosion",
            [emitterSubEffect.ShellEmit]: "Shell Emission",
            [emitterType.Particle]: "Particle",
            [emitterType.Instance]: "Instance",
            [instance.Arrow1]: "Arrow1",
            [instance.Arrow2]: "Arrow2",
            [instance.Missile1]: "Missile1",
            [instance.Missile2]: "Missile2",
            [instance.Missile3]: "Missile3",
            [instance.Missile4]: "Missile4",
            [instance.Missile5]: "Missile5",
            [instance.Missile6]: "Missile6",
            [instance.Missile7]: "Missile7",
            [instance.Missile8]: "Missile8",
            [instance.Missile9]: "Missile9",
            [instance.Building1]: "Building1",
            [instance.Building2]: "Building2",
            [instance.Weapon1]: "Weapon1",
            [instance.Weapon2]: "Weapon2",
            [instance.Airplane1]: "Airplane1",
            [behaviourMode.FindEnemy]: "Find enemy",
            [behaviourMode.EscapeWhenEnemeyNear]: "Escape when enemy is nearby",
            [idleMode.WaitInPlace]: "Wait in place",
            [idleMode.RoamAndWander]: "Roaming",
            [nearAttackTargetMode.None]: "None",
            // [nearAttackTargetMode.Charge]: "Charge",
            // [nearAttackTargetMode.JumpForward]: "Jump Forward",
            [attackMode.SideShift]: "Side shift",
            [attackMode.KeepDistance]: "Keep distance",
            [remoteAttackMode.ShootAroundObstacles]: "Shoot around obstacles",
            [behaviourModeKey.FindEnemyDistanceFactor]: "Find enemy distance factor",
            [behaviourModeKey.PursuitDistanceFactor]: "Pursuit distance factor",
            [behaviourModeKey.EscapeDistanceFactor]: "Escape distance factor",
            [behaviourModeKey.NearDistanceFactor]: "Enemy proximity distance factor",
            [idleModeKey.RoamAndWanderDistanceFactor]: "Roaming distance factor",
            [nearAttackTargetModeKey.CD]: "Cooldown time",
            [nearAttackTargetModeKey.DamageInterval]: "Damage interval",
            [nearAttackTargetModeKey.DistanceFactor]: "Distance Factor",
            [nearAttackTargetModeKey.ForceFactor]: "Force Factor",
            [nearAttackTargetModeKey.SpeedFactor]: "Speed Factor",
        },
    }
}

export let getTextDataByVariable = (): languageTextDataByVariable => {
    return {
        [language.Chinese]: {
            [languageVariableKey.LimitMaxCount]: (value: number) => `最多选择${value}个`,
            [languageVariableKey.LimitFileSize]: (value: number) => `文件大小超过了${value}MB`,
        },
        [language.English]: {
            [languageVariableKey.LimitMaxCount]: (value: number) => `Can select ${value} at most`,
            [languageVariableKey.LimitFileSize]: (value: number) => `File size exceeds ${value}MB`,
        },
    }
}