open Sinon

let buildService = (
  ~sandbox,
  ~init=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~clear=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~render=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~beforeExec=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~afterExec=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~setStyle=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~beginWindow=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~endWindow=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~beginChild=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~endChild=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~setNextWindowRect=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~addFBOTexture=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~getWindowBarHeight=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~getContext=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~button=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~setCursorPos=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~loadImage=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~asset=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~handleDragDropTarget=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~menu=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~sceneTree=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~inspector=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  ~switchButton=createEmptyStub(refJsObjToSandbox(sandbox.contents)),
  (),
): Meta3dImguiRendererProtocol.ServiceType.service => {
  {
    init,
    clear,
    render,
    beforeExec,
    afterExec,
    setStyle,
    beginWindow,
    endWindow,
    beginChild,
    endChild,
    setNextWindowRect,
    addFBOTexture,
    getWindowBarHeight,
    getContext,
    button,
    setCursorPos,
    loadImage,
    asset,
    handleDragDropTarget: handleDragDropTarget->Obj.magic,
    menu,
    sceneTree,
    inspector,
    switchButton,
  }
}
