"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getAllPublishContributes = exports.getAllPublishExtensions = exports.getAllPublishContributeProtocols = exports.getAllPublishExtensionProtocols = exports.isLoginSuccess = exports.registerUser = exports.checkUserName = exports.init = exports.error = void 0;
const ErrorService = require("./application_layer/common/ErrorService");
const BackendService = require("./application_layer/common/BackendService");
const LoginService = require("./application_layer/user/LoginService");
const RegisterService = require("./application_layer/user/RegisterService");
const ShopService = require("./application_layer/shop/ShopService");
exports.error = ErrorService.error;
exports.init = BackendService.init;
exports.checkUserName = RegisterService.checkUserName;
exports.registerUser = RegisterService.register;
exports.isLoginSuccess = LoginService.isLoginSuccess;
exports.getAllPublishExtensionProtocols = ShopService.getAllPublishExtensionProtocols;
exports.getAllPublishContributeProtocols = ShopService.getAllPublishContributeProtocols;
exports.getAllPublishExtensions = ShopService.getAllPublishExtensions;
exports.getAllPublishContributes = ShopService.getAllPublishContributes;
