let buildComponentContribute = (
  ~componentName="componentA",
  ~createStateFunc=(. config) => Obj.magic(1),
  ~getGameObjectsFunc=(. state, _) => Obj.magic(1),
  ~createComponentFunc=(. state) => (state, Obj.magic(1)),
  ~addComponentFunc=(. state, _, _) => state,
  ~removeComponentFunc=(. state, _, _) => state,
  ~hasComponentFunc=(. state, _) => false,
  ~getComponentFunc=(. state, _) => Obj.magic(1),
  ~getComponentsFunc=(. state, _) => [],
  ~getNeedDisposedComponentsFunc=(. state) => [],
  ~getAllComponentsFunc=(. state) => Obj.magic(1),
  ~getComponentDataFunc=(. state, _, _) => Obj.magic(1),
  ~setComponentDataFunc=(. state, _, _, _) => state,
  ~deferDisposeComponentFunc=(. state, _) => state,
  ~batchDisposeComponentsFunc=(. state, _) => state,
  (),
): Meta3dEngineCoreProtocol.RegisterComponentType.componentContribute => {
  componentName: componentName,
  createStateFunc: createStateFunc,
  getGameObjectsFunc: getGameObjectsFunc,
  createComponentFunc: createComponentFunc,
  addComponentFunc: addComponentFunc,
  removeComponentFunc: removeComponentFunc,
  hasComponentFunc: hasComponentFunc,
  getComponentFunc: getComponentFunc,
  getComponentsFunc: getComponentsFunc,
  getNeedDisposedComponentsFunc: getNeedDisposedComponentsFunc,
  getAllComponentsFunc: getAllComponentsFunc,
  getComponentDataFunc: getComponentDataFunc,
  setComponentDataFunc: setComponentDataFunc,
  deferDisposeComponentFunc: deferDisposeComponentFunc,
  batchDisposeComponentsFunc: batchDisposeComponentsFunc,
}
