name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: yarn install --force && yarn bootstrap

    - name: Unit Test
      run: yarn ci:test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: 4facce3d-d742-4d11-8f12-47ed5e43be1d
